USE Healthcare;
CREATE TABLE IF NOT EXISTS LiteratureReview (
    reference_id INT AUTO_INCREMENT PRIMARY KEY,
    citation TEXT,
    link TEXT
);

INSERT INTO LiteratureReview (citation, link) VALUES
('R. Saracco, "Digital Transformation in Healthcare," IEEE Digital Reality White Paper, Feb. 2020', 'https://digitalreality.ieee.org/images/files/pdf/Digital_Transformation_in_HealthcareFINAL.pdf'),
('N. Ostern, G. Perscheid, C. Reelitz, and J. Moormann, "Keeping pace with the healthcare transformation: a literature review and research agenda for a new decade of health information systems research," Electronic Markets, vol. 31, pp. 901-921, 2021', 'https://link.springer.com/article/10.1007/s12525-021-00484-1'),
('T. Reller, T. Eva, and W. Gunn, "Access for patients – and other ways to get Elsevier articles without a subscription," Elsevier, Jan. 2020', 'https://www.elsevier.com/connect/access-for-patients-and-other-ways-to-get-elsevier-articles-without-a-subscription'),
('"Big Data Analytics in Healthcare — A Systematic Literature Review and Roadmap," IEEE Journal of Automation and Systems, vol. 7, no. 1, pp. 1-15, 2020', 'https://ieee-jas.net/article/doi/10.1109/JAS.2020.1003384?pageType=en'),
('"Healthcare predictive analytics using machine learning and deep learning," Journal of Engineering and Technology, vol. 12, no. 2, pp. 45-58, 2023', 'https://jesit.springeropen.com/articles/10.1186/s43067-023-00108-y'),
('"Health Care - Recent articles and discoveries," SpringerLink, 2025', 'https://link.springer.com/subject/health-care');

INSERT INTO LiteratureReview (citation, link) VALUES
('AIEEE one of IEEE journal talks about the application of AI in healthcare. It states that AI enables doctors to make better decisions, which leads to better patient care by the analysis of data and making treatment personalized. AI can scale the processing of huge data to be done fast enough for pattern recognition and along with this prediction of patient health. Better diagnosis and treatment plan', ''),
('Another IEEE paper talks about the use of digital technologies to improve the flow of healthcare operations and data accessibility. Digital transformation in healthcare: putting healthcare providers and tech together with the integration of healthcare technology such as EHRs, telemedicine and mobile health applications. These tools can be used to bridge the alliance between providers and patients, cut paperwork, and so enhance the quality of care provided.', ''),
('Elsevier has some work on managing the woes of healthcare data management. Another one stresses the necessity of low-latency, highly available database platforms to eliminate redundancy and preserve correct data from all over analysis. Healthcare data is generally siloed away across systems, which could lead to wrong decision making and bureaucracy. A secure and scalable database system is the backbone of a centralized data storage wherein only accurate data with the latest history is available to any patient. It makes care better and decreases the probability of medical errors.', ''),
('Elsevier is yet again published paper which states how excellent data management leads to better delivery of healthcare by consolidating data systems. Access to the centralized data systems for healthcare providers means they can retrieve and interrogate patient data reliably to make decisions that will improve patient outcomes. Such systems also enable sharing of data across different health care facilities, to make it easier collaboration and improve continuity of care.', ''),
('Springer has articles on Healthcare data management (all systems) Study: Digital database systems also are a part of how we will store records and the improvements to health delivery for patients. Notes on the need for data privacy and user-friendly services among healthcare workers. Data security is very essential in healthcare so as to protect patient privacy and simultaneously be in-formation of such things as HIPAA. We need easier interfaces for the healthcare professionals to add patient data and get information, minimizing operator errors and increasing efficiency.', ''),
('Springer categorizes another article under management science measures to improve healthcare operations and policy-making that relies on the appropriate data management. Through the use of tools like data analytics and predictive modeling, statutes aimed at maximizing efficiency in the operations of healthcare organizations and lowering costs while helping bettering quality of care. These methods also can guide policy decisions, revealing the direction of healthcare trends and outcomes.', '');
